/**
 * seo.mjs — regression checks for the indexable surface of the site.
 *
 * These run under Node only: they read the generated files off disk, which the
 * browser suite in tests.js cannot do. Run them with `node tests/node.mjs`.
 *
 * What they are for: every page a search engine sees is generated by
 * scripts/build-seo.mjs from src/tool-registry.js, and nothing until now
 * noticed when the two drifted apart, or when a page quietly stopped being
 * indexable. Each check below exists because getting it wrong is silent —
 * the site still looks fine in a browser while the page falls out of the index.
 */

import { readFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { assert } from './tests.js';
import { getTools, getCategories } from '../src/tool-registry.js';
import { PRODUCTION_ORIGIN } from '../src/config.js';
import { toolPage, categoryPage, dialogsMarkup } from '../scripts/build-seo.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const seoTests = [];
function test(name, group, fn) {
  seoTests.push({ name, group, fn });
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

const cache = new Map();
async function page(relativePath) {
  if (!cache.has(relativePath)) {
    cache.set(relativePath, readFile(join(root, relativePath), 'utf8'));
  }
  return cache.get(relativePath);
}

function attr(html, pattern) {
  return html.match(pattern)?.[1] ?? null;
}

const canonicalOf = (html) => attr(html, /<link rel="canonical" href="([^"]+)"/);
const titleOf = (html) => attr(html, /<title>([\s\S]*?)<\/title>/);
const descriptionOf = (html) => attr(html, /<meta name="description" content="([^"]*)"/);
const robotsOf = (html) => attr(html, /<meta name="robots" content="([^"]*)"/);
const ogUrlOf = (html) => attr(html, /<meta property="og:url" content="([^"]+)"/);

function headingsOf(html) {
  return [...html.matchAll(/<h1[^>]*>([\s\S]*?)<\/h1>/g)].map((m) => m[1].replace(/<[^>]+>/g, '').trim());
}

/** Every internal href on the page, deduplicated, fragments and queries dropped. */
function internalLinks(html) {
  const hrefs = [...html.matchAll(/href="(\/[^"#?]*)"/g)].map((m) => m[1]);
  return [...new Set(hrefs)];
}

/** Map a site path to the file that serves it, the way Cloudflare Pages does. */
function fileFor(path) {
  if (path === '/') return 'index.html';
  const clean = path.replace(/^\//, '');
  if (clean.endsWith('/')) return clean + 'index.html';
  if (/\.[a-z0-9]+$/i.test(clean)) return clean;
  return clean + '.html'; // /privacy is served by privacy.html
}

async function exists(relativePath) {
  try {
    await access(join(root, relativePath));
    return true;
  } catch {
    return false;
  }
}

/** Every page that is meant to be indexed, as [sitePath, filePath]. */
function indexablePages() {
  const entries = [
    ['/', 'index.html'],
    ['/tools/', 'tools/index.html'],
    ['/privacy', 'privacy.html'],
    ['/terms', 'terms.html'],
  ];
  for (const group of getCategories()) {
    entries.push(['/tools/' + group.slug + '/', 'tools/' + group.slug + '/index.html']);
  }
  for (const tool of getTools()) {
    entries.push(['/' + tool.slug + '/', tool.slug + '/index.html']);
  }
  return entries;
}

/* ------------------------------------------------------------------ *
 * Page existence and head metadata
 * ------------------------------------------------------------------ */

test('Every page in the registry exists on disk', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    assert.ok(await exists(file), 'missing generated page: ' + file);
  }
});

test('Every page has a self-referencing canonical on the production origin', 'SEO pages', async () => {
  for (const [path, file] of indexablePages()) {
    const canonical = canonicalOf(await page(file));
    assert.equal(
      canonical,
      PRODUCTION_ORIGIN + path,
      file + ' has a canonical that does not point at its own URL: ' + canonical,
    );
  }
});

test('No two pages claim the same canonical URL', 'SEO pages', async () => {
  const seen = new Map();
  for (const [, file] of indexablePages()) {
    const canonical = canonicalOf(await page(file));
    assert.ok(!seen.has(canonical), canonical + ' is claimed by both ' + seen.get(canonical) + ' and ' + file);
    seen.set(canonical, file);
  }
});

test('og:url agrees with the canonical', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    const html = await page(file);
    assert.equal(ogUrlOf(html), canonicalOf(html), file + ' has an og:url that disagrees with its canonical');
  }
});

test('Every page title is unique and not empty', 'SEO pages', async () => {
  const seen = new Map();
  for (const [, file] of indexablePages()) {
    const title = titleOf(await page(file));
    assert.ok(title && title.trim().length > 10, file + ' has no usable <title>');
    assert.ok(!seen.has(title), 'duplicate title on ' + seen.get(title) + ' and ' + file + ': ' + title);
    seen.set(title, file);
  }
});

test('Every page has a meta description of a sensible length', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    const description = descriptionOf(await page(file));
    assert.ok(description, file + ' has no meta description');
    assert.ok(
      description.length >= 50 && description.length <= 200,
      file + ' meta description is ' + description.length + ' characters; aim for 50-200',
    );
  }
});

test('Every page has exactly one non-empty h1', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    const headings = headingsOf(await page(file));
    assert.equal(headings.length, 1, file + ' has ' + headings.length + ' h1 elements, expected 1');
    assert.ok(headings[0].length > 0, file + ' has an empty h1');
  }
});

test('No indexable page carries a noindex directive', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    const robots = robotsOf(await page(file));
    assert.ok(robots, file + ' has no robots meta tag');
    assert.ok(!/noindex/i.test(robots), file + ' is marked noindex: ' + robots);
  }
});

test('Structured data on every page is valid JSON', 'SEO pages', async () => {
  for (const [, file] of indexablePages()) {
    const blocks = [...(await page(file)).matchAll(
      /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,
    )];
    for (const [, body] of blocks) {
      let parsed;
      try {
        parsed = JSON.parse(body.replace(/<\\\//g, '</'));
      } catch (error) {
        throw new Error(file + ' has JSON-LD that does not parse: ' + error.message);
      }
      assert.ok(parsed['@context'], file + ' has JSON-LD with no @context');
      assert.ok(parsed['@type'], file + ' has JSON-LD with no @type');
    }
  }
});

/* ------------------------------------------------------------------ *
 * The content a crawler actually reads
 * ------------------------------------------------------------------ */

test('Supporting content sits outside #app, where app.js cannot clear it', 'SEO content', async () => {
  // This is the check that earns its keep. app.js calls clearNode(#app) on
  // boot, so anything nested inside #app is absent from the rendered DOM —
  // which is the DOM Google indexes. Putting the page notes back inside #app
  // would look completely fine in a browser and quietly empty every page.
  for (const tool of getTools()) {
    const html = await page(tool.slug + '/index.html');
    const appStart = html.indexOf('<div id="app"');
    const appEnd = html.indexOf('</div>', appStart);
    const notesAt = html.indexOf('class="seo-body"');
    assert.ok(notesAt !== -1, tool.slug + ' has no supporting content at all');
    assert.ok(
      notesAt > appEnd,
      tool.slug + ' keeps its supporting content inside #app, so app.js deletes it on boot',
    );
  }

  const home = await page('index.html');
  const homeAppEnd = home.indexOf('</div>', home.indexOf('<div id="app"'));
  assert.ok(
    home.lastIndexOf('data-seo-tool="home"') > homeAppEnd,
    'the homepage keeps its own content inside #app, so app.js deletes it on boot',
  );
});

test('Every tool page carries enough supporting content to be worth indexing', 'SEO content', async () => {
  for (const tool of getTools()) {
    const html = await page(tool.slug + '/index.html');
    const body = html.slice(html.indexOf('class="seo-body"'), html.indexOf('</main>'));
    const words = body.replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/g, ' ').split(/\s+/).filter(Boolean).length;
    // The floor is set just under the thinnest page that exists today. Google
    // had declined to index nine of these when they carried roughly 90 words
    // of rendered content, so this guards the change that fixed them.
    assert.ok(words >= 200, tool.slug + ' has only ' + words + ' words of supporting content');
  }
});

test('Every tool page links to related tools that exist', 'SEO content', async () => {
  const slugs = new Set(getTools().map((tool) => tool.slug));
  for (const tool of getTools()) {
    const html = await page(tool.slug + '/index.html');
    const start = html.indexOf('<h2>Related tools</h2>');
    const section = html.slice(start, html.indexOf('</ul>', start));
    const links = [...section.matchAll(/href="\/([a-z0-9-]+)\/"/g)].map((m) => m[1]);
    assert.ok(links.length >= 2, tool.slug + ' offers only ' + links.length + ' related tools');
    for (const slug of links) {
      assert.ok(slugs.has(slug), tool.slug + ' links to a related tool that does not exist: ' + slug);
    }
    assert.ok(!links.includes(tool.slug), tool.slug + ' lists itself as a related tool');
  }
});

test('Every internal link resolves to a file that is served', 'SEO content', async () => {
  for (const [, file] of indexablePages()) {
    for (const link of internalLinks(await page(file))) {
      const target = fileFor(link);
      assert.ok(await exists(target), file + ' links to ' + link + ', which nothing serves');
    }
  }
});

test('No page ships template or editorial scaffolding to readers', 'SEO content', async () => {
  // The privacy and terms pages used to carry a "this is a template, not legal
  // advice" banner and a bracketed note addressed to the site operator. Both
  // were indexable, and /privacy ranks. Nothing like that goes out again.
  const forbidden = [/\[Operator[:\s]/i, /this is a template/i, /\bTODO\b(?!\s+—\s+cURL)/, /\bFIXME\b/, /lorem ipsum/i];
  for (const [, file] of indexablePages()) {
    const html = await page(file);
    for (const pattern of forbidden) {
      assert.ok(!pattern.test(html), file + ' still contains ' + pattern + ' in public copy');
    }
  }
});

/* ------------------------------------------------------------------ *
 * Sitemap, robots and headers
 * ------------------------------------------------------------------ */

test('The sitemap lists exactly the indexable pages', 'SEO sitemap', async () => {
  const xml = await page('sitemap.xml');
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
  const expected = indexablePages().map(([path]) => PRODUCTION_ORIGIN + path);

  assert.equal(new Set(locs).size, locs.length, 'the sitemap lists the same URL twice');
  for (const url of expected) {
    assert.ok(locs.includes(url), 'missing from the sitemap: ' + url);
  }
  for (const url of locs) {
    assert.ok(expected.includes(url), 'the sitemap lists a URL no page claims: ' + url);
  }
});

test('Every sitemap entry is on the production origin and has a real lastmod', 'SEO sitemap', async () => {
  const xml = await page('sitemap.xml');
  for (const [, url] of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
    assert.ok(url.startsWith(PRODUCTION_ORIGIN + '/'), 'sitemap URL is off-origin: ' + url);
  }
  const today = new Date().toISOString().slice(0, 10);
  for (const [, date] of xml.matchAll(/<lastmod>([^<]+)<\/lastmod>/g)) {
    assert.ok(/^\d{4}-\d{2}-\d{2}$/.test(date), 'malformed lastmod: ' + date);
    assert.ok(date <= today, 'lastmod is in the future: ' + date);
  }
});

test('robots.txt allows crawling and points at the sitemap', 'SEO sitemap', async () => {
  const txt = await page('robots.txt');
  assert.ok(/^User-agent: \*$/m.test(txt), 'robots.txt has no wildcard user-agent group');
  assert.ok(/^Allow: \/$/m.test(txt), 'robots.txt does not allow the site root');
  assert.ok(
    txt.includes('Sitemap: ' + PRODUCTION_ORIGIN + '/sitemap.xml'),
    'robots.txt does not point at the production sitemap',
  );
  const disallows = [...txt.matchAll(/^Disallow: (.+)$/gm)].map((m) => m[1].trim());
  assert.equal(disallows.filter(Boolean).length, 0, 'robots.txt blocks a path: ' + disallows.join(', '));
});

test('No X-Robots-Tag header covers a public page', 'SEO sitemap', async () => {
  const headers = await page('_headers');
  const blocks = headers.split(/\n(?=\S)/);
  for (const block of blocks) {
    if (!/X-Robots-Tag:\s*[^\n]*noindex/i.test(block)) continue;
    const path = block.trim().split(/\s|\n/)[0];
    assert.ok(
      path.startsWith('/tests/') || path.startsWith('/scripts/'),
      'a noindex header covers ' + path + ', which serves public pages',
    );
  }
});

/* ------------------------------------------------------------------ *
 * Drift between the generator and what is checked in
 * ------------------------------------------------------------------ */

test('Generated pages match what build-seo.mjs would write today', 'SEO build', async () => {
  // Without this, editing tool-registry.js and forgetting to rebuild ships a
  // page describing a tool that no longer behaves that way, and nothing says so.
  const dialogs = await dialogsMarkup();
  for (const tool of getTools()) {
    const expected = await toolPage(tool, dialogs);
    const actual = await page(tool.slug + '/index.html');
    assert.equal(actual, expected, tool.slug + '/index.html is stale — run: node scripts/build-seo.mjs');
  }
  assert.equal(await page('tools/index.html'), categoryPage(null, true), 'tools/index.html is stale — run: node scripts/build-seo.mjs');
  for (const group of getCategories()) {
    assert.equal(
      await page('tools/' + group.slug + '/index.html'),
      categoryPage(group, false),
      'tools/' + group.slug + '/index.html is stale — run: node scripts/build-seo.mjs',
    );
  }
});

export { seoTests };
